[GLOBAL]
pants_version = "2.12.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
]
#
#pants.backend.docker = [
#  "poetry"
#]

[source]
root_patterns = ["/"]
[python]
tailor_ignore_solitary_init_files = false

[python-infer]
inits = true

[anonymous-telemetry]
enabled = false
