[GLOBAL]
pants_version = "2.12.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
]

[python]
tailor_ignore_solitary_init_files = false

[python-infer]
inits = true

[anonymous-telemetry]
enabled = false
