python_sources()

python_tests(
    name="tests0",
)
python_requirement(
    name="opentelemetry.exporter.otlp.proto.grpc.trace_exporter",
    requirements=["opentelemetry-exporter-otlp-proto-grpc>=1.10.0"],
    modules=["custom_module"],
)