name: Makefile CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3

      - name: make
        run: make all