name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.10
      with:
        repository_username: ${{ secrets.PYPI_USERNAME }}
        repository_password: ${{ secrets.PYPI_PASSWORD }}
