name: Semantic Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Semantic Release
        run: |
          pip install python-semantic-release
          semantic-release publish --noop --verbosity=debug -D version_variable="pyproject.toml:version" -D upload_to_release=true
